class Product {
  final int id;
  final String productName, productImage, productCategory, productDescription;
  final double productPrice;
  final bool isRecommendation, isBestSellings;

  Product({
    this.id,
    this.productName,
    this.productImage,
    this.productCategory,
    this.productDescription,
    this.productPrice,
    this.isRecommendation,
    this.isBestSellings
  });
}

List<Product> products = [
  // =================================================================
  // Candies
  // =================================================================
  Product(
    id: 1,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/candies/candies-1.jpg',
    productCategory: 'candies',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 2,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/candies/candies-2.jpg',
    productCategory: 'candies',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 3,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/candies/candies-3.jpg',
    productCategory: 'candies',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 0.50,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 4,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/candies/candies-4.jpg',
    productCategory: 'candies',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 0.50,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 5,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/candies/candies-5.jpg',
    productCategory: 'candies',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 0.75,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 6,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/candies/candies-6.jpg',
    productCategory: 'candies',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: true,
  ),
  // =================================================================
  // Drinks
  // =================================================================
  Product(
    id: 7,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/drinks-1.jpg',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: true,
  ),
  Product(
    id: 8,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/drinks-2.jpg',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 9,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/drinks-3.jpg',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 10,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/drinks-4.jpg',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 11,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/drinks-5.jpg',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 12,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/drinks-6.jpg',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 13,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/drinks-7.jpg',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: true,
  ),
  Product(
    id: 14,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/beer-1.png',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 15,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/beer-2.png',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 16,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/beer-3.jpg',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 17,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/beer-4.png',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 18,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/milk-1.jpg',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 19,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/milk-2.jpg',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 21,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/milk-3.jpg',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 22,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/milk-4.jpg',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 23,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/milk-5.jpg',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 24,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/yogurt-1.jpg',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 25,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/yogurt-2.jpg',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 26,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/yogurt-3.jpg',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 27,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/water-1.png',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 0.50,
    isRecommendation: true,
    isBestSellings: false,
  ),
  Product(
    id: 28,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/drinks/water-2.jpg',
    productCategory: 'drinks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.50,
    isRecommendation: false,
    isBestSellings: false,
  ),
  // =================================================================
  // Fruits
  // =================================================================
  Product(
    id: 29,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/fruits/fruits-1.jpg',
    productCategory: 'fruits',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 30,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/fruits/fruits-2.jpg',
    productCategory: 'fruits',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: true,
    isBestSellings: false,
  ),
  Product(
    id: 31,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/fruits/fruits-3.jpg',
    productCategory: 'fruits',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 32,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/fruits/fruits-4.jpg',
    productCategory: 'fruits',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 33,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/fruits/fruits-5.jpg',
    productCategory: 'fruits',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 34,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/fruits/fruits-6.jpg',
    productCategory: 'fruits',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  // =================================================================
  // Noodles
  // =================================================================
  Product(
    id: 35,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/noodles/noodles-1.jpg',
    productCategory: 'noodles',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.25,
    isRecommendation: true,
    isBestSellings: false,
  ),
  Product(
    id: 36,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/noodles/noodles-2.jpg',
    productCategory: 'noodles',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.25,
    isRecommendation: false,
    isBestSellings: true,
  ),
  Product(
    id: 37,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/noodles/noodles-3.jpg',
    productCategory: 'noodles',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.25,
    isRecommendation: true,
    isBestSellings: false,
  ),
  Product(
    id: 38,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/noodles/noodles-4.jpg',
    productCategory: 'noodles',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.25,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 39,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/noodles/noodles-5.jpg',
    productCategory: 'noodles',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.25,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 40,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/noodles/noodles-6.jpg',
    productCategory: 'noodles',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.25,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 41,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/noodles/noodles-7.jpg',
    productCategory: 'noodles',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 1.25,
    isRecommendation: false,
    isBestSellings: false,
  ),
  // =================================================================
  // Snacks
  // =================================================================
  Product(
    id: 42,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/doritos-1.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 43,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/doritos-2.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 44,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/doritos-3.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 45,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/doritos-4.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 46,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/doritos-5.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 47,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/doritos-6.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 48,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/ferreo-rocher.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 49,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/kitkat-1.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: true,
    isBestSellings: false,
  ),
  Product(
    id: 50,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/kitkat-2.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 51,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/kitkat-3.png',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 52,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/lays-1.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 53,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/lays-2.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 54,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/lays-3.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 55,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/lays-4.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 56,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/lays-5.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 57,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/lays-6.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 58,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/oreo-1.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 59,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/oreo-2.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 60,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/pringles-1.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: true,
  ),
  Product(
    id: 61,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/pringles-2.jpg',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
  Product(
    id: 62,
    productName: 'Lorem Ipsum',
    productImage: 'assets/images/snacks/pringles-3.png',
    productCategory: 'snacks',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nulla nunc, suscipit non egestas et, tempor quis est. In hac habitasse platea dictumst. Donec luctus sapien ac ultrices sodales.',
    productPrice: 2.00,
    isRecommendation: false,
    isBestSellings: false,
  ),
];
